options:
  version:
    type: string
    description: "The version of npm-offline-registry to install. Can also be a revision or tag when using the repo/repo_type options."
  registry_name:
    type: string
    description: "The name of the upstream registry used to generate the NPM cache."
    default: "registry.npmjs.org"
  enable_failover:
    type: boolean
    description: "Whether or not to fetch unknown packages from the upstream registry."
    default: true
  local_registry:
    type: string
    description: "The externally accessable address for this registry."
  enable_static_server:
    type: boolean
    description: "Optionally use a static file server to serve package tarballs."
    default: true
  repo:
    type: string
    description: "Location for an SCM repository to install npm-offline-registry from, can be a git, hg or svn URI"
  repo_type:
    type: string
    description: "Type of SCM to install from, when using the repo config option, can be git, hg or svn."
